Se atiende el issues #141
SIU-Toba/framework pull request #142
Opened 2022-09-23 13:30 UTC by feder102

2022-09-23 21:28 UTC, sergiovier requested changes

2022-09-23 21:28 UTC, sergiovier commented on php/nucleo/lib/toba_rest.php
> -			$settings['api_minor'] = $datos_ini_proyecto['proyecto']['api_minor'];
Primero, leer "api_major" desde [api_v1], si no existe leer de [proyecto]. no hay que eliminar esto, tiene que quedar por BC.

2022-09-26 12:58 UTC, feder102 commented on php/nucleo/lib/toba_rest.php
> -			$settings['api_minor'] = $datos_ini_proyecto['proyecto']['api_minor'];
Ok Sergio! ahora hago los cambios necesarios para esto.

2022-10-14 22:08 UTC, enfoqueNativo commented on php/nucleo/lib/toba_rest.php
> +		$api_nombre = $_SERVER['REDIRECT_API_NOMBRE'] ?? 'v1';
@feder102 la "version" de la api viene en el param del metodo, no hay valor default ya que debe funcionar tanto para apis versionadas como clasicas.

2022-10-14 22:09 UTC, enfoqueNativo commented on php/nucleo/lib/toba_rest.php
> +		}
Quizas se podria meter en un metodo y clavar un `array_merge` con el resultado.

2022-10-18 21:12 UTC, feder102 commented
@enfoqueNativo hice varios cambios y los probé en guaraní! fijate si ahí esta mas limpio !

2022-11-02 21:25 UTC, enfoqueNativo requested changes
Ta mas lindo... pero soy quisqui :stuck_out_tongue:

2022-11-02 21:25 UTC, enfoqueNativo commented on php/nucleo/lib/toba_rest.php
> +		}
```suggestion
                $indx = 'api_' . $api;
		if (isset($datos_ini_proyecto[$indx]['api_major']) && isset($datos_ini_proyecto[$indx]['api_minor'])) {
			$settings_1['api_version'] = "v{$datos_ini_proyecto[$indx]['api_major']}.{$datos_ini_proyecto[$indx]['api_minor']}";
			$settings_1['api_major'] = $datos_ini_proyecto[$indx]['api_major'];
			$settings_1['api_minor'] = $datos_ini_proyecto[$indx]['api_minor'];
		}
```

2022-11-02 21:25 UTC, enfoqueNativo commented on php/nucleo/lib/toba_rest.php
> +		$datos_ini_proyecto = $this->get_ini_proyecto();
Esto lo recibiria como parametro, achica la cantidad de datos del merge final y te permite no enviar cosas de mas al arreglo `settings` en el metodo que invoca.

2022-12-19 20:49 UTC, enfoqueNativo commented on php/nucleo/lib/toba_rest.php
> +		return $datos_ini_proyecto;
No se necesita todo, solo los datos correspondientes a lo que determina este metodo, osea la version.

2022-12-19 20:51 UTC, enfoqueNativo commented on php/nucleo/lib/toba_rest.php
> +		$datos_ini_proyecto = $this->get_param_major_minor($api, $this->get_ini_proyecto());
Esto tiene que ir a otra variable, sino estas devuelviendo cosas de mas en `get_param_major_minor` para salvaguardar el condicional que sigue.

2022-12-19 20:52 UTC, enfoqueNativo commented on php/nucleo/lib/toba_rest.php
> +		$settings = array_merge($settings, $ini->get('settings', null, array(), false),$datos_ini_proyecto);
Aca se mergea la variable nueva unicamente.

2022-12-21 12:27 UTC, feder102 commented on php/nucleo/lib/toba_rest.php
> +		return $datos_ini_proyecto;
Necesitamos asignar _api_version_ se usa en la info de la **API**. Ademas se hace un chequeo de las variables del proyecto.ini como indica el método _get_param_major_minor_ en sus comentarios.
creería que debería estar o dividir el metodo en dos! uno que arme la variable con los api_major y api_minor; otro con la api_version

2022-12-21 12:33 UTC, feder102 commented on php/nucleo/lib/toba_rest.php
> +		return $datos_ini_proyecto;
```suggestion
		//Si no existen subconjuntos api_<version> utilizó (api_major:api_minor) de [proyecto] proyecto.ini
```

2022-12-26 15:54 UTC, enfoqueNativo commented on php/nucleo/lib/toba_rest.php
> +		return $datos_ini_proyecto;
@feder102 No me estoy explicando bien probablemente, me refiero a que ninguna otra entrada de `proyecto.ini` tiene que salir de este metodo, lo unico que debe devolver son aquellos datos que determina independientemente de lo que llegue por parametro.

2022-12-26 15:55 UTC, enfoqueNativo commented on php/nucleo/lib/toba_rest.php
> +		$datos_ini_proyecto = $this->get_param_major_minor($api, $this->get_ini_proyecto());
Pa haerlo mas grafico, mientras esto sea asignado a `$datos_ini_proyecto`... no va a pasar!

2022-12-26 15:56 UTC, enfoqueNativo commented on php/nucleo/lib/toba_rest.php
> +		$settings = array_merge($settings, $ini->get('settings', null, array(), false),$datos_ini_proyecto);
Vai a tener que revertir este cambio, por `nueva variable` me referia a la que tendrias que haber creado en el coment anterior ;)

2023-02-01 15:40 UTC, enfoqueNativo requested changes
Ahi te deje un comment y un suggest.

2023-02-01 15:40 UTC, enfoqueNativo commented on php/nucleo/lib/toba_rest.php
> +		$datos_proyecto			= 	array_merge($datos_ini_proyecto, $datos_api_major_minor);
Con que necesidad haria este merge?, no se necesita en lo absoluto

2023-02-01 15:40 UTC, enfoqueNativo commented on php/nucleo/lib/toba_rest.php
> +		$settings = array_merge($settings,$ini->get('settings', null, array(), false),$datos_proyecto);
```suggestion
		$settings = array_merge($settings,$ini->get('settings', null, array(), false),$datos_api_major_minor);
```

2023-03-13 18:56 UTC, sergiovier commented on php/nucleo/lib/toba_rest.php
> +			$datos_api['api_version'] = "v{$datos_ini_proyecto[$indx]['api_major']}.{$datos_ini_proyecto[$indx]['api_minor']}";
¿la versión de la API es para armar el formato de info?

```
{
    "version": "1.4.1\n",
    "nombre": "Documentos-Frontend",
    "api": "1.1",
    "api_major": "1",
    "api_minor": "1"
}
```

Si es así, estas haciendo **v1.0** ....

2023-08-31 17:19 UTC, sergiovier commented on php/nucleo/lib/toba_rest.php
> +			$datos_api['api_version'] = "v{$datos_ini_proyecto[$indx]['api_major']}.{$datos_ini_proyecto[$indx]['api_minor']}";
Me refiero a la V delante major.minor como algo que no era parte de lo que especificamos.

2023-08-31 21:05 UTC, enfoqueNativo commented on php/nucleo/lib/toba_rest.php
> +			$datos_api['api_version'] = "v{$datos_ini_proyecto[$indx]['api_major']}.{$datos_ini_proyecto[$indx]['api_minor']}";
No se si era parte, esta [asi](https://github.com/SIU-Toba/framework/blob/develop/php/nucleo/lib/toba_rest.php#L85) hace rato, en algun momento charlamos de sacarlo pero se ve que no lo llevamos adelante.

Igual este PR lo tengo que cerrar xq no me deja subir cambios aca, hice el #164 que continua con lo que veniamos aca.

2023-08-31 21:05 UTC, closed without merging