Agrega el procesamiento del parametro de linea de comando --alias-nuc…
SIU-Toba/framework pull request #153
Opened 2023-04-21 12:33 UTC by alfrenovsky

El parametro de linea de comando --alias-nucleo figura en la ayuda de "bin/toba instalacion" pero no era procesado y siempre era preguntado de forma interactiva.

Este commit agrega el procesamiento de ese parametro de linea de comando en la funcion definir_alias_nucleo.

2023-04-21 13:35 UTC, enfoqueNativo requested changes
@alfrenovsky Mas alla del detalle de la indentación, te pido ese cambio asi homogeneizamos el comportamiento con el comando `instalacion_silenciosa`.

El comando `crear` (para la instalacion basica) no debe hacer uso del parametro.
Gracias.

2023-04-21 13:35 UTC, enfoqueNativo commented on php/consola/comandos/comando_instalacion.php
> +    $param = $this->get_parametros();
Podrias convertir la variable `$param` en un parametro formal con default `array()`?, ya que este [metodo](https://github.com/SIU-Toba/framework/blob/develop/php/consola/comandos/comando_instalacion.php#L110) es el unico que lo expone como parametro a la consola, en el resto de los casos debe ser ingresado por prompt

2023-04-21 14:29 UTC, alfrenovsky commented on php/consola/comandos/comando_instalacion.php
> +    $param = $this->get_parametros();
Si --alias-nucleo no va a funcionar en la instalacion normal no deberia estar en el help. Tampoco deberia tener la opcion --no-interactivo si con esa opcion sigue siendo interactivo.


Ahi me di cuenta de la indentacion. Disculpas.

2023-04-21 14:33 UTC, alfrenovsky commented on php/consola/comandos/comando_instalacion.php
> +    $param = $this->get_parametros();
> Podrias convertir la variable `$param` en un parametro formal con default `array()`?, ya que este [metodo](https://github.com/SIU-Toba/framework/blob/develop/php/consola/comandos/comando_instalacion.php#L110) es el unico que lo expone como parametro a la consola, en el resto de los casos debe ser ingresado por prompt

En la ayuda figura --alias-nucleo como opcion de parametro de linea de comando. Copie la forma en que estaba hecho en otras funciones dentro del mismo archivo.

2023-04-21 14:38 UTC, alfrenovsky commented
> @alfrenovsky Mas alla del detalle de la indentación, te pido ese cambio asi homogeneizamos el comportamiento con el comando `instalacion_silenciosa`.
> 
> El comando `crear` (para la instalacion basica) no debe hacer uso del parametro. Gracias.

En ese caso deberia rechazars este pull request.
Voy a ver si lo puedo hacer andar con instalacion_silenciosa que tambien me fuerza interacción.

2023-04-24 12:22 UTC, alfrenovsky commented
> @alfrenovsky Mas alla del detalle de la indentación, te pido ese cambio asi homogeneizamos el comportamiento con el comando `instalacion_silenciosa`.
> 
> El comando `crear` (para la instalacion basica) no debe hacer uso del parametro. Gracias.

En instalacion_silenciosa lo correcto sería que tome alias-nucleo del parametro de lines de comando --alias-nucleo o que lo tome del yaml?

2023-04-24 13:16 UTC, enfoqueNativo commented on php/consola/comandos/comando_instalacion.php
> +    $param = $this->get_parametros();
> Si --alias-nucleo no va a funcionar en la instalacion normal no deberia estar en el help. Tampoco deberia tener la opcion --no-interactivo si con esa opcion sigue siendo interactivo.
> 
> Ahi me di cuenta de la indentacion. Disculpas.

Quizas no me explique correctamente o se genero un malentendido, la clase que modificaste posee diversos subcomandos de los cuales:

- Crear: meramente genera una carpeta con archivos de configuracion para el uso de otros comandos y no acepta el modificador planteado
- Instalar: es  un wrapper de varios comandos distintos para que el usuario no realice todos esos pasos y acepta los modificadores planteados en el help. Que no funcione correctamente es justamente el bug que intentas solucionar con este PR.

Respecto del flag `--no-interactivo` es un trabajo de fusion (con el comando `instalacion_silenciosa`) que quedo a medio terminar, si te interesa podes abrir un nuevo PR que conjugue ambos.

> En la ayuda figura --alias-nucleo como opcion de parametro de linea de comando. Copie la forma en que estaba hecho en otras funciones dentro del mismo archivo.

Lo se, por ello te solicite el cambio para que funcione de acuerdo a como deberia y no a como nos quedo en el codigo bugueado.

2023-04-24 13:20 UTC, enfoqueNativo commented
> > @alfrenovsky Mas alla del detalle de la indentación, te pido ese cambio asi homogeneizamos el comportamiento con el comando `instalacion_silenciosa`.
> > El comando `crear` (para la instalacion basica) no debe hacer uso del parametro. Gracias.
> 
> En instalacion_silenciosa lo correcto sería que tome alias-nucleo del parametro de lines de comando --alias-nucleo o que lo tome del yaml?

Deberia de aceptarlo de la linea de comandos, no recuerdo que se haya definido entrada para el archivo yml.

2023-05-29 18:54 UTC, enfoqueNativo commented
Se cierra por falta de respuesta, se replico el cambio en [3aba795198ae4512eccf8ad6c7dc41ac6cb8becf]

2023-05-29 18:54 UTC, closed without merging