Mejora cierre conexión DB desde Jasper
SIU-Toba/framework pull request #159
Opened 2023-06-27 15:06 UTC by lleonardis

GDS 64293
Issue #313: https://gitlab.siu.edu.ar/siu/soporte/-/issues/313

2023-06-27 19:24 UTC, enfoqueNativo requested changes

2023-06-27 19:24 UTC, enfoqueNativo commented on php/nucleo/lib/salidas/toba_vista_jasperreports.php
> +                        toba::logger()->error("Jasper JDBC Connection Error");
```suggestion
                        toba::logger()->error('Error en la ejecución del reporte');
```
No sabes cual es la fuente del error, por eso guardas el msg.

2023-06-29 18:25 UTC, lleonardis commented on php/nucleo/lib/salidas/toba_vista_jasperreports.php
> +                        toba::logger()->error("Jasper JDBC Connection Error");
@enfoqueNativo Listo, corregido!!!

2023-06-29 19:17 UTC, enfoqueNativo approved these changes

2023-06-29 19:18 UTC, enfoqueNativo approved these changes

2023-06-29 19:20 UTC, merged